name: Publish @debugg-ai/cli to NPM

on:
  push:
    branches: [main]
    tags:
      - 'v*'
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      version_type:
        description: 'Version type'
        required: true
        default: 'patch'
        type: choice
        options:
        - patch
        - minor
        - major
      publish:
        description: 'Publish to NPM'
        required: true
        default: true
        type: boolean

permissions:
  contents: write
  id-token: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Run lint
      run: npm run lint

    - name: Run tests
      run: npm run test

    - name: Build project
      run: npm run build

    - name: Test build output
      run: |
        if [ ! -f "dist/cli.js" ]; then
          echo "CLI build output not found"
          exit 1
        fi
        if [ ! -f "dist/index.js" ]; then
          echo "Index build output not found"
          exit 1
        fi

  cli-test:
    runs-on: ubuntu-latest
    needs: test
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Build project
      run: npm run build

    - name: Test CLI help command
      run: |
        node dist/cli.js --help
        if [ $? -ne 0 ]; then
          echo "CLI help command failed"
          exit 1
        fi

    - name: Test CLI version
      run: |
        node dist/cli.js --version
        if [ $? -ne 0 ]; then
          echo "CLI version command failed"
          exit 1
        fi

    - name: Test programmatic API
      run: |
        node -e "const { DEFAULT_CONFIG } = require('./dist/index.js'); console.log('API loaded successfully');"
        if [ $? -ne 0 ]; then
          echo "Programmatic API test failed"
          exit 1
        fi

  publish:
    needs: [test, cli-test]
    runs-on: ubuntu-latest
    if: (github.event_name == 'push' && github.ref == 'refs/heads/main' && !contains(github.event.head_commit.message, '[skip ci]')) || github.event_name == 'release' || (github.event_name == 'workflow_dispatch' && inputs.publish) || startsWith(github.ref, 'refs/tags/v')
    permissions:
      contents: write
      packages: write
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Fetch full history for proper versioning
        
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        registry-url: 'https://registry.npmjs.org'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci

    - name: Configure git
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"

    - name: Auto bump version (push to main)
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      run: |
        # Get current version from package.json
        CURRENT_VERSION=$(node -p "require('./package.json').version")
        echo "Current version: $CURRENT_VERSION"
        
        # Bump patch version automatically
        npm version patch --no-git-tag-version
        NEW_VERSION=$(node -p "require('./package.json').version")
        echo "NEW_VERSION=$NEW_VERSION" >> $GITHUB_ENV
        echo "New version: $NEW_VERSION"
        
        # Commit and tag the new version
        git add package.json
        git commit -m "chore: auto-bump version to $NEW_VERSION [skip ci]"
        git tag "v$NEW_VERSION"
        git push origin main --follow-tags

    - name: Bump version (workflow_dispatch)
      if: github.event_name == 'workflow_dispatch'
      run: |
        npm version ${{ inputs.version_type }} --no-git-tag-version
        NEW_VERSION=$(node -p "require('./package.json').version")
        echo "NEW_VERSION=$NEW_VERSION" >> $GITHUB_ENV
        git add package.json
        git commit -m "chore: bump version to $NEW_VERSION"
        git tag "v$NEW_VERSION"
        git push origin main
        git push origin "v$NEW_VERSION"

    - name: Get version from tag (release/tag)
      if: github.event_name == 'release' || startsWith(github.ref, 'refs/tags/v')
      run: |
        if [[ "${{ github.event_name }}" == "release" ]]; then
          VERSION="${{ github.event.release.tag_name }}"
        else
          VERSION="${GITHUB_REF#refs/tags/}"
        fi
        VERSION=${VERSION#v}
        echo "VERSION=$VERSION" >> $GITHUB_ENV
        npm version $VERSION --no-git-tag-version --allow-same-version
        
    - name: Build project
      run: npm run build
      
    - name: Publish to NPM
      run: npm publish --access public
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        
    - name: Create GitHub Release (workflow_dispatch)
      if: github.event_name == 'workflow_dispatch' && env.NEW_VERSION
      uses: softprops/action-gh-release@v2
      with:
        tag_name: v${{ env.NEW_VERSION }}
        name: Release v${{ env.NEW_VERSION }}
        body: |
          ## @debugg-ai/cli v${{ env.NEW_VERSION }}
          
          CLI tool for running DebuggAI tests in CI/CD environments like GitHub Actions.
          
          ## Features
          - 🧪 Generate E2E tests from git changes
          - 🚀 GitHub Actions integration
          - 📊 Test artifact downloads (scripts, recordings, results)
          - ⚡ Local development server integration
          - 📋 Test suite management and status checking
          
          ## Installation
          ```bash
          npm install -g @debugg-ai/cli
          ```
          
          ## Usage
          ```bash
          # Run tests with API key
          debugg-ai test --api-key YOUR_API_KEY
          
          # Use with environment variable
          export DEBUGGAI_API_KEY=your_api_key
          debugg-ai test --wait-for-server
          ```
          
          See [README.md](https://github.com/debugg-ai/debugg-ai-extensions/tree/main/debugg-ai-cli#readme) for detailed usage instructions.
        draft: false
        prerelease: false